include: package:flutter_lints/flutter.yaml

custom_lint:
  rules:
    - missing_provider_scope: false
    - avoid_manual_providers_as_generated_provider_dependency: false

linter:
  rules:
    prefer_single_quotes: true
