name: flutter_turnkey_test
description: "Flutter project for turnkey test. This will use News API to fetch
  news and explore the content that is provided, having features like search,
  bookmark, and explore."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  sembast: ^3.7.1+2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/env/
